---
- name: Include HAProxy installation task
  ansible.builtin.include_tasks: install.yml
  when: flush_all != true

- name: Include HAProxy uninstallation task
  ansible.builtin.include_tasks: uninstall.yml
  when: flush_all == true